import { Project } from "@/types";

/**
 * Seed data for Firestore database
 *
 * This file contains sample project data used to populate the database
 * during development and testing. The data structure matches the Project
 * interface exactly, minus the 'id' field which is auto-generated by Firestore.
 *
 * To add new projects:
 * 1. Copy an existing project object
 * 2. Update all fields with new data
 * 3. Ensure dates are in ISO string format
 * 4. Use real Unsplash URLs for images
 * 5. Run `npm run seed` to update the database
 */
export const seedProjects: Omit<Project, "id">[] = [
  {
    projectNumber: "217",
    name: "Luxury Master Bathroom Remodel",
    category: "bathroom",
    briefDescription:
      "Complete master bathroom renovation with spa-like features and premium finishes",
    longDescription:
      "This comprehensive master bathroom remodel transformed a dated 1990s space into a luxurious spa-like retreat. The project included removing the old tub-shower combo and installing a spacious walk-in shower with frameless glass enclosure, rainfall showerhead, and body jets. We added a stunning freestanding soaking tub positioned beneath a large window for natural light. The double vanity features custom cabinetry with soft-close drawers, quartz countertops, and undermount sinks. Heated tile flooring throughout ensures comfort year-round. The space also includes a separate water closet for privacy and upgraded lighting with dimmers for ambiance control.",
    thumbnail:
      "https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=800&h=600&fit=crop",

    // PM information
    pms: [{ name: "Mike Johnson" }],

    // Media and documents - empty for seed data, can be added later
    pictures: [],
    documents: [],
    logs: [],

    // Location and client details
    location: "Austin, TX - Westlake Hills",
    clientInfo: {
      name: "Jennifer & Robert Martinez",
      address: "2847 Scenic Ridge Drive, Austin, TX 78746",
      phone: "(512) 555-0198",
      email: "jennifer.martinez@email.com",
    },

    // Project timeline
    projectDates: {
      startDate: "2024-01-15T09:00:00.000Z",
      completionDate: "2024-03-10T17:00:00.000Z",
      estimatedCompletion: "2024-03-15T17:00:00.000Z",
    },

    status: "completed",

    // Metadata
    createdAt: "2024-01-10T14:30:00.000Z",
    updatedAt: "2024-03-10T17:00:00.000Z",

    // Additional details
    tags: [
      "master bathroom",
      "walk-in shower",
      "freestanding tub",
      "heated floors",
      "spa bathroom",
      "luxury remodel",
    ],
    estimatedCost: 52000,
    actualCost: 49800,
  },

  {
    projectNumber: "304A",
    name: "Modern Guest Bathroom Update",
    category: "bathroom",
    briefDescription:
      "Fresh, contemporary update to guest bathroom with new fixtures and finishes",
    longDescription:
      "This guest bathroom refresh focused on modernizing the space while working within a moderate budget. We updated all fixtures including a new toilet, vanity, and faucets with contemporary chrome finishes. The old builder-grade mirror was replaced with a stylish framed mirror and updated lighting fixtures. Fresh paint in a soft gray palette brightened the space, and new hardware throughout completed the modern look. We also installed a new medicine cabinet for additional storage and upgraded the exhaust fan for better ventilation. The existing tile was in good condition, so we kept it and updated the grout for a fresh appearance.",
    thumbnail:
      "https://images.unsplash.com/photo-1620626011761-996317b8d101?w=800&h=600&fit=crop",

    pms: [{ name: "Sarah Wilson" }],

    pictures: [],
    documents: [],
    logs: [],

    location: "Austin, TX - Hyde Park",
    clientInfo: {
      name: "David Chen",
      address: "1523 Duval Street, Austin, TX 78701",
      phone: "(512) 555-0242",
      email: "david.chen@email.com",
    },

    projectDates: {
      startDate: "2024-02-05T08:00:00.000Z",
      completionDate: "2024-02-18T16:00:00.000Z",
      estimatedCompletion: "2024-02-20T16:00:00.000Z",
    },

    status: "completed",

    createdAt: "2024-01-28T10:15:00.000Z",
    updatedAt: "2024-02-18T16:00:00.000Z",

    tags: [
      "guest bathroom",
      "budget remodel",
      "modern fixtures",
      "quick renovation",
    ],
    estimatedCost: 8500,
    actualCost: 8200,
  },

  {
    projectNumber: "189",
    name: "Open Concept Kitchen Transformation",
    category: "kitchen",
    briefDescription:
      "Removed wall to create stunning open-concept kitchen with custom island",
    longDescription:
      "This major kitchen renovation involved removing a load-bearing wall to open up the kitchen to the dining and living areas, creating a beautiful open-concept floor plan perfect for entertaining. We installed a structural beam to support the ceiling, then completely redesigned the kitchen layout. The centerpiece is a large custom island with seating for four, featuring a waterfall edge quartz countertop and built-in wine storage. All-new custom cabinetry in a soft white finish with shaker-style doors provides ample storage. We installed high-end stainless steel appliances including a 48-inch range, built-in refrigerator, and quiet dishwasher. The backsplash features handmade subway tiles in a classic herringbone pattern. Pendant lighting over the island and under-cabinet LED lighting complete the sophisticated look.",
    thumbnail:
      "https://images.unsplash.com/photo-1556912172-45b7abe8b7e1?w=800&h=600&fit=crop",

    pms: [{ name: "Mike Johnson" }, { name: "Carlos Martinez" }],

    pictures: [],
    documents: [],
    logs: [],

    location: "Austin, TX - Tarrytown",
    clientInfo: {
      name: "Amanda & Steven Rodriguez",
      address: "3156 Windsor Road, Austin, TX 78703",
      phone: "(512) 555-0367",
      email: "amanda.rodriguez@email.com",
    },

    projectDates: {
      startDate: "2024-01-08T07:30:00.000Z",
      completionDate: "2024-03-22T18:00:00.000Z",
      estimatedCompletion: "2024-03-30T18:00:00.000Z",
    },

    status: "completed",

    createdAt: "2023-12-15T11:00:00.000Z",
    updatedAt: "2024-03-22T18:00:00.000Z",

    tags: [
      "open concept",
      "structural work",
      "custom island",
      "high-end appliances",
      "complete remodel",
      "entertaining space",
    ],
    estimatedCost: 78000,
    actualCost: 75500,
  },

  {
    projectNumber: "311B",
    name: "Farmhouse Kitchen Refresh",
    category: "kitchen",
    briefDescription:
      "Charming farmhouse-style kitchen update with shiplap and vintage details",
    longDescription:
      "This kitchen refresh embraced modern farmhouse style while maintaining the home's character. We painted the existing cabinets in a warm cream color and added new brushed brass hardware for a vintage touch. A custom range hood with shiplap detail became the focal point of the space. We installed butcher block countertops for warmth and functionality, perfect for the client's love of cooking. The backsplash features classic white subway tiles with dark grout for contrast. Open shelving replaced some upper cabinets, displaying the client's collection of vintage dishes. We added a farmhouse sink with a bridge faucet and installed new lighting including a statement chandelier over the breakfast nook. The existing hardwood floors were refinished to complete the cohesive look.",
    thumbnail:
      "https://images.unsplash.com/photo-1556911220-bff31c812dba?w=800&h=600&fit=crop",

    pms: [{ name: "Sarah Wilson" }],

    pictures: [],
    documents: [],
    logs: [],

    location: "Austin, TX - Bouldin Creek",
    clientInfo: {
      name: "Emily Thompson",
      address: "1842 South 3rd Street, Austin, TX 78704",
      phone: "(512) 555-0421",
      email: "emily.thompson@email.com",
    },

    projectDates: {
      startDate: "2024-02-12T08:00:00.000Z",
      completionDate: "2024-03-15T17:00:00.000Z",
      estimatedCompletion: "2024-03-18T17:00:00.000Z",
    },

    status: "completed",

    createdAt: "2024-02-01T09:30:00.000Z",
    updatedAt: "2024-03-15T17:00:00.000Z",

    tags: [
      "farmhouse style",
      "cabinet painting",
      "butcher block",
      "shiplap",
      "vintage details",
      "budget friendly",
    ],
    estimatedCost: 32000,
    actualCost: 30800,
  },
];
